<?php

use Illuminate\Database\Seeder;

class AttributesListTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'all-classics','name'=>'All Classics']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'american-classics','name'=>'American Classics']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'boats','name'=>'Boats']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'british-classics','name'=>'British Classics']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'formula-cars','name'=>'Formula Cars']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'french-classics','name'=>'French Classics']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'german-classics','name'=>'German Classics']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'japanese-classics','name'=>'Japanese Classics']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'military-vehicles','name'=>'Military Vehicles']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mopeds-2','name'=>'Mopeds']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'motorcycles','name'=>'Motorcycles']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'abarth','name'=>'Abarth']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'abbott','name'=>'Abbott']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ac','name'=>'AC']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'acura','name'=>'Acura']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'adler','name'=>'Adler']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'aero','name'=>'Aero']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ahrens-fox','name'=>'Ahrens Fox']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ajs','name'=>'AJS']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'alfa-romeo','name'=>'Alfa Romeo']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'allard','name'=>'Allard']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'allemano','name'=>'Allemano']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'alpina-bmw','name'=>'Alpina (BMW)']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'alta','name'=>'Alta']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'alvis','name'=>'Alvis']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'amc','name'=>'AMC']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'american-bantam','name'=>'American Bantam']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'american-underslung','name'=>'American Underslung']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'amga','name'=>'AMGA']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'amilcar','name'=>'Amilcar']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'amphicar','name'=>'Amphicar']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'apal','name'=>'Apal']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'apollo','name'=>'Apollo']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'arden','name'=>'Arden']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'aries','name'=>'Aries']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'armstrong-siddeley','name'=>'Armstrong Siddeley']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'arnolt','name'=>'Arnolt']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'arrows','name'=>'Arrows']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'asa','name'=>'Asa']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ashley','name'=>'Ashley']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'asquith','name'=>'Asquith']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'aston-martin','name'=>'Aston Martin']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'attila','name'=>'Attila']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'auburn','name'=>'Auburn']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'audi','name'=>'Audi']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'austin','name'=>'Austin']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'austin-healey','name'=>'Austin Healey']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'authi','name'=>'Authi']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'auto-union','name'=>'Auto Union']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'autobianchi','name'=>'Autobianchi']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'autocar','name'=>'Autocar']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'avanti','name'=>'Avanti']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'b-w-a','name'=>'B.W.A.']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'baci','name'=>'Baci']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ballot','name'=>'Ballot']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'bandini','name'=>'Bandini']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'bantam','name'=>'Bantam']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'barkas','name'=>'Barkas']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'barris-ohrberg','name'=>'Barris/Ohrberg']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'batmobile','name'=>'Batmobile']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'bayliss-thomas','name'=>'Bayliss Thomas']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'beauford','name'=>'Beauford']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'bedford','name'=>'Bedford']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'benova','name'=>'Benova']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'bentley','name'=>'Bentley']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'berkeley','name'=>'Berkeley']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'berliet','name'=>'Berliet']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'birchall','name'=>'Birchall']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'bitter','name'=>'Bitter']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'bizzarrini','name'=>'Bizzarrini']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'blakely','name'=>'Blakely']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'blerck','name'=>'Blerck']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'bmw','name'=>'BMW']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'bond','name'=>'Bond']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'bonnet','name'=>'Bonnet']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'borgward','name'=>'Borgward']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'bra','name'=>'BRA']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'brabham','name'=>'Brabham']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'bricklin','name'=>'Bricklin']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'bristol','name'=>'Bristol']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'british-salmson','name'=>'British Salmson']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'bsa','name'=>'BSA']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'buckingham','name'=>'Buckingham']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'buckler','name'=>'Buckler']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'bugatti','name'=>'Bugatti']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'buick','name'=>'Buick']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'burlington','name'=>'Burlington']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'burton','name'=>'Burton']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'cadillac','name'=>'Cadillac']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'camen-fiordelisi','name'=>'Camen Fiordelisi']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'cameron','name'=>'Cameron']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'cannon','name'=>'Cannon']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'carver','name'=>'Carver']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'caterham','name'=>'Caterham']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'chalmers','name'=>'Chalmers']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'chandler','name'=>'Chandler']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'checker','name'=>'Checker']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'chenard','name'=>'Chenard']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'chenard-walcker','name'=>'Chenard-Walcker']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'chesil','name'=>'Chesil']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'chevrolet','name'=>'Chevrolet']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'chevron','name'=>'Chevron']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'chrysler','name'=>'Chrysler']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'cisitalia','name'=>'Cisitalia']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'cisitalia-abarth','name'=>'Cisitalia-Abarth']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'citroen','name'=>'Citroën']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'clan','name'=>'Clan']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'clenet','name'=>'Clenet']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'cleveland','name'=>'Cleveland']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'clyno','name'=>'Clyno']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'commer','name'=>'Commer']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'connaught','name'=>'Connaught']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'cooper','name'=>'Cooper']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'cord','name'=>'Cord']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'crosley','name'=>'Crosley']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'cunningham','name'=>'Cunningham']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'daf','name'=>'DAF']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'daimler','name'=>'Daimler']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'damilla','name'=>'Damilla']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'datsun','name'=>'Datsun']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'de-tomaso','name'=>'De','name'=>'Tomaso']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'delage','name'=>'Delage']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'delahaye','name'=>'Delahaye']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'delaugere','name'=>'Delaugere']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'delaunay-belleville','name'=>'Delaunay Belleville']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'dellow','name'=>'Dellow']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'delorean','name'=>'DeLorean']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'deluca','name'=>'DeLuca']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'dennis','name'=>'Dennis']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'denzel','name'=>'Denzel']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'desoto','name'=>'DeSoto']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'devin','name'=>'Devin']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'diatto','name'=>'Diatto']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'diva','name'=>'Diva']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'dkw','name'=>'DKW']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'dodge','name'=>'Dodge']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'dolson','name'=>'Dolson']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'donkervoort','name'=>'Donkervoort']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'donnet-zedel','name'=>'Donnet-Zedel']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'dual','name'=>'Dual']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'duesenberg','name'=>'Duesenberg']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'dune','name'=>'Dune']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'durant','name'=>'Durant']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'dutton','name'=>'Dutton']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ebro','name'=>'Ebro']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'edsel','name'=>'Edsel']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'elva','name'=>'Elva']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'emw','name'=>'EMW']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'enzmann','name'=>'Enzmann']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ermini','name'=>'Ermini']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'erskine','name'=>'Erskine']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'essex','name'=>'Essex']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'evante','name'=>'Evante']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'everett-morrison','name'=>'Everett-Morrison']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'excalibur','name'=>'Excalibur']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'excelsior','name'=>'Excelsior']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'facel-vega','name'=>'Facel Vega']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'fairthorpe','name'=>'Fairthorpe']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'falcon','name'=>'Falcon']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ferrari','name'=>'Ferrari']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'fiat','name'=>'Fiat']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'fisker','name'=>'Fisker']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'flajole','name'=>'Flajole']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'fleur-de-lys','name'=>'Fleur de Lys']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'fn','name'=>'FN']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ford','name'=>'Ford']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'franklin','name'=>'Franklin']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'frazer-nash','name'=>'Frazer Nash']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'freightliner','name'=>'Freightliner']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'fso','name'=>'FSO']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'fuldamobil','name'=>'Fuldamobil']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'fuller','name'=>'Fuller']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'gardner-douglas','name'=>'Gardner Douglas']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'gatso','name'=>'Gatso']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'gaz','name'=>'Gaz']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'gazelle','name'=>'Gazelle']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'georges-irat','name'=>'Georges Irat']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'georges-richard','name'=>'Georges Richard']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'giannini','name'=>'Giannini']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'gilbern','name'=>'Gilbern']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ginetta','name'=>'Ginetta']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'glas','name'=>'Glas']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'gmc','name'=>'GMC']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'gobron-brillie','name'=>'Gobron-Brillie']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'goggomobil','name'=>'Goggomobil']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'goliath','name'=>'Goliath']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'gordon-keeble','name'=>'Gordon Keeble']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'gorkovski','name'=>'Gorkovski']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'graham-paige','name'=>'Graham Paige']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'grd','name'=>'GRD']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'griffith','name'=>'Griffith']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'gsm','name'=>'GSM']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'gutbrod','name'=>'Gutbrod']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'hanomag','name'=>'Hanomag']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'hansa','name'=>'Hansa']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'he-herbert-engineering','name'=>'HE (Herbert Engineering)']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'healey','name'=>'Healey']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'heinkel','name'=>'Heinkel']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'hillman','name'=>'Hillman']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'hino','name'=>'Hino']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'hispano-suiza','name'=>'Hispano-Suiza']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'hobbycar','name'=>'Hobbycar']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'holden','name'=>'Holden']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'holley','name'=>'Holley']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'honda','name'=>'Honda']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'horch','name'=>'Horch']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'hornet','name'=>'Hornet']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'hotchkiss','name'=>'Hotchkiss']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'hrg','name'=>'HRG']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'hudson','name'=>'Hudson']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'humber','name'=>'Humber']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'hummer','name'=>'Hummer']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'hupmobile','name'=>'Hupmobile']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'hurtan','name'=>'Hurtan']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'hyundai','name'=>'Hyundai']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ifa','name'=>'IFA']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'imperial','name'=>'Imperial']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'infinity','name'=>'Infinity']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'innocenti','name'=>'Innocenti']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'intermeccanica','name'=>'Intermeccanica']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'international','name'=>'International']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'invicta','name'=>'Invicta']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'isetta','name'=>'Isetta']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'iso','name'=>'Iso']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'isotta-fraschini','name'=>'Isotta Fraschini']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'isuzu','name'=>'Isuzu']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'iveco','name'=>'Iveco']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'jaguar','name'=>'Jaguar']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'jeep','name'=>'Jeep']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'jensen','name'=>'Jensen']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'jewett','name'=>'Jewett']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'johnson','name'=>'Johnson']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'jowett','name'=>'Jowett']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'jzr','name'=>'JZR']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'k1','name'=>'K1']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'kaiser','name'=>'Kaiser']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'kellison','name'=>'Kellison']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'kissel','name'=>'Kissel']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'kleinschnittger','name'=>'Kleinschnittger']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'koenigsegg','name'=>'Koenigsegg']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'kougar','name'=>'Kougar']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'la-licorne','name'=>'La','name'=>'Licorne']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lacroix-delaville','name'=>'Lacroix&amp; DeLaville']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lada','name'=>'Lada']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lagonda','name'=>'Lagonda']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lamborghini','name'=>'Lamborghini']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lanchester','name'=>'Lanchester']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lancia','name'=>'Lancia']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'land-rover','name'=>'Land Rover']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lasalle','name'=>'LaSalle']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'leon-bollee','name'=>'Léon Bollée']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lea-francis','name'=>'Lea Francis']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'legend','name'=>'Legend']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'leitch','name'=>'Leitch']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lenham','name'=>'Lenham']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lexus','name'=>'Lexus']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'leyland','name'=>'Leyland']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ligier','name'=>'Ligier']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lincoln','name'=>'Lincoln']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lister','name'=>'Lister']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lloyd','name'=>'Lloyd']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lmx','name'=>'LMX']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'locomobile','name'=>'Locomobile']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lola','name'=>'Lola']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lomax','name'=>'Lomax']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lombardi','name'=>'Lombardi']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'lotus','name'=>'Lotus']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'luego','name'=>'Luego']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mack','name'=>'Mack']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'madison','name'=>'Madison']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'magirus-deutz','name'=>'Magirus-Deutz']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'man','name'=>'Man']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'marauder','name'=>'Marauder']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'march','name'=>'March']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'marcos','name'=>'Marcos']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'marendaz','name'=>'Marendaz']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'marlin','name'=>'Marlin']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'marmon','name'=>'Marmon']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'marquette','name'=>'Marquette']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'maserati','name'=>'Maserati']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'matford','name'=>'Matford']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mathis','name'=>'Mathis']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'matra','name'=>'Matra']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'maxwell','name'=>'Maxwell']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'maybach','name'=>'Maybach']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mazda','name'=>'Mazda']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mcdowell','name'=>'McDowell']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mclaren','name'=>'McLaren']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mega','name'=>'Mega']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mercedes-benz','name'=>'Mercedes-Benz']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mercer','name'=>'Mercer']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mercury','name'=>'Mercury']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'merlin','name'=>'Merlin']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'messerschmitt','name'=>'Messerschmitt']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'metz','name'=>'Metz']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mg','name'=>'MG']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'michelotti','name'=>'Michelotti']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'michigan','name'=>'Michigan']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'midas','name'=>'Midas']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'miller','name'=>'Miller']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'minerva','name'=>'Minerva']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mini','name'=>'Mini']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mitchell','name'=>'Mitchell']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mitsubishi','name'=>'Mitsubishi']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mochet','name'=>'Mochet']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'monarch','name'=>'Monarch']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'monica','name'=>'Monica']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'monteverdi','name'=>'Monteverdi']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'moon','name'=>'Moon']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mopeds','name'=>'Mopeds']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'moretti','name'=>'Moretti']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'morgan','name'=>'Morgan']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'morris','name'=>'Morris']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'moskvich','name'=>'Moskvich']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'moss','name'=>'Moss']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mowag','name'=>'Mowag']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'moyer','name'=>'Moyer']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'muntz','name'=>'Muntz']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'mvs','name'=>'MVS']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'nagant','name'=>'Nagant']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'nardi','name'=>'Nardi']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'nash','name'=>'Nash']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'naylor','name'=>'Naylor']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'neckar','name'=>'Neckar']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ng','name'=>'NG']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'nissan','name'=>'Nissan']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'noble','name'=>'Noble']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'nsu','name'=>'NSU']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'oakland','name'=>'Oakland']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ogle','name'=>'Ogle']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'oldsmobile','name'=>'Oldsmobile']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'opel','name'=>'Opel']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'orchid','name'=>'Orchid']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'osca','name'=>'OSCA']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'osi','name'=>'OSI']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'other-carmakes','name'=>'Other carmakes']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'overland','name'=>'Overland']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'packard','name'=>'Packard']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'pagani','name'=>'Pagani']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'paige','name'=>'Paige']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'panhard','name'=>'Panhard']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'panhard-et-levassor','name'=>'Panhard et Levassor']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'panoz','name'=>'Panoz']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'panther','name'=>'Panther']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'paramount','name'=>'Paramount']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'peerless','name'=>'Peerless']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'pegaso','name'=>'Pegaso']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'pembleton','name'=>'Pembleton']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'peugeot','name'=>'Peugeot']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'pgo','name'=>'PGO']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'phoenix','name'=>'Phoenix']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'pierce-arrow','name'=>'Pierce-Arrow']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'pilgrim','name'=>'Pilgrim']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'piper','name'=>'Piper']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'plymouth','name'=>'Plymouth']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'pobeda','name'=>'Pobeda']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'pontiac','name'=>'Pontiac']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'pope-hartford','name'=>'Pope Hartford']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'porsche','name'=>'Porsche']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'praga','name'=>'Praga']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'proteus','name'=>'Proteus']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'puma','name'=>'Puma']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'qvale','name'=>'Qvale']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'raf','name'=>'Raf']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'railton','name'=>'Railton']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'rally-cars','name'=>'Rally Cars']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ram','name'=>'RAM']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'rambler','name'=>'Rambler']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'regal','name'=>'Regal']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'reliant','name'=>'Reliant']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'renault','name'=>'Renault']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'rene-bonnet','name'=>'Rene Bonnet']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'reo','name'=>'REO']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'riley','name'=>'Riley']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'roamer','name'=>'Roamer']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'robur','name'=>'Robur']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'rochdale','name'=>'Rochdale']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'rolls-royce','name'=>'Rolls-Royce']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ronart','name'=>'Ronart']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'rondeau','name'=>'Rondeau']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'roselli','name'=>'Roselli']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'rosengarth','name'=>'Rosengarth']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'rover','name'=>'Rover']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'rovin','name'=>'Rovin']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'royale','name'=>'Royale']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'rugby','name'=>'Rugby']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ruska','name'=>'Ruska']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'saab','name'=>'Saab']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'sabra','name'=>'Sabra']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'sachsenring','name'=>'Sachsenring']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'saleen','name'=>'Saleen']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'salmson','name'=>'Salmson']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'sam-cree','name'=>'Sam Cree']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'sanford','name'=>'Sanford']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'santarsiero','name'=>'Santarsiero']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'saturn','name'=>'Saturn']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'saurer','name'=>'Saurer']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'scania','name'=>'Scania']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'seat','name'=>'Seat']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'sebring','name'=>'Sebring']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'shadow','name'=>'Shadow']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'shelby','name'=>'Shelby']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'siata','name'=>'Siata']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'simca','name'=>'Simca']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'singer','name'=>'Singer']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'skoda','name'=>'Skoda']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'smart','name'=>'Smart']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'sovam','name'=>'Sovam']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'spartan','name'=>'Spartan']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'speedwell','name'=>'Speedwell']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'spyker','name'=>'Spyker']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'squire','name'=>'Squire']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ss-cars-jaguar','name'=>'SS Cars Jaguar']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'standard','name'=>'Standard']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'stanguellini-colli','name'=>'Stanguellini Colli']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'star','name'=>'Star']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'stevens-duryea','name'=>'Stevens Duryea']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'steyr-puch','name'=>'Steyr-Puch']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'stoddard-dayton','name'=>'Stoddard Dayton']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'stola','name'=>'Stola']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'studebaker','name'=>'Studebaker']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'stutz','name'=>'Stutz']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'subaru','name'=>'Subaru']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'suffolk','name'=>'Suffolk']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'sunbeam','name'=>'Sunbeam']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'superformance','name'=>'Superformance']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'suzuki','name'=>'Suzuki']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'swallow','name'=>'Swallow']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'swallow-doretti','name'=>'Swallow Doretti']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'talbot','name'=>'Talbot']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'tatra','name'=>'Tatra']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'teal-engineering','name'=>'Teal Engineering']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'templar','name'=>'Templar']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'tempo','name'=>'Tempo']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'terraplane','name'=>'Terraplane']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'tesla','name'=>'Tesla']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'thomas-detroit','name'=>'Thomas Detroit']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'thurner-nsu','name'=>'Thurner (NSU)']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'tiffany','name'=>'Tiffany']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'tiga','name'=>'Tiga']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'tornado','name'=>'Tornado']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'toyota','name'=>'Toyota']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'trabant','name'=>'Trabant']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'tractors','name'=>'Tractors']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'trident','name'=>'Trident']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'trike','name'=>'Trike']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'triumph','name'=>'Triumph']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'trojan','name'=>'Trojan']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'tucker','name'=>'Tucker']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'turner','name'=>'Turner']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'tvr','name'=>'TVR']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ultima','name'=>'Ultima']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'umap','name'=>'Umap']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'unic','name'=>'Unic']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'unipower','name'=>'Unipower']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'vaillant','name'=>'Vaillant']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'vanden-plas','name'=>'Vanden Plas']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'vauxhall','name'=>'Vauxhall']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'velorex','name'=>'Velorex']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'venturi','name'=>'Venturi']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'veritas','name'=>'Veritas']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'vespa','name'=>'Vespa']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'vincke','name'=>'Vincke']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'voisin','name'=>'Voisin']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'volga','name'=>'Volga']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'volkswagen','name'=>'Volkswagen']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'volvo','name'=>'Volvo']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'vulcan','name'=>'Vulcan']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'walter','name'=>'Walter']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'wanderer','name'=>'Wanderer']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'ward-lafrance','name'=>'Ward LaFrance']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'wartburg','name'=>'Wartburg']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'warwick','name'=>'Warwick']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'westfield','name'=>'Westfield']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'whitgift','name'=>'Whitgift']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'wiesmann','name'=>'Wiesmann']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'willys','name'=>'Willys']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'winnebago','name'=>'Winnebago']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'winton','name'=>'Winton']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'wolseley','name'=>'Wolseley']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'xtc','name'=>'XTC']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'yamaha','name'=>'Yamaha']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'zagato','name'=>'Zagato']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'zastava','name'=>'Zastava']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'zedel','name'=>'Zedel']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'zimmer','name'=>'Zimmer']);
        \App\AttributeList::create(['attributeID'=>1, 'slug' => 'zolfe','name'=>'Zolfe']);


    }
}
